import React from 'react'

function HomePage(props) {
  return (
    <div className='home'>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum repellendus nulla adipisci quia error tenetur cumque labore perspiciatis? Magni sit iure officiis dolorum, provident aut expedita, delectus numquam odio cumque explicabo sapiente dicta deleniti? Necessitatibus doloremque error quod earum hic deserunt odio, porro suscipit esse! Earum minus quo repellat soluta adipisci aliquid dolore, culpa non aut! Corrupti ipsa fuga pariatur! Eligendi blanditiis deleniti ducimus expedita voluptates at, vel doloremque autem in dolore commodi nobis obcaecati beatae cum a quae! Accusantium laudantium voluptates minima, repellat sunt ab libero iste similique impedit ipsum esse debitis autem illum dicta labore non nam error natus illo magni asperiores quidem. Totam laudantium est fugit ducimus itaque. Nulla consequuntur accusamus quisquam facere nihil voluptates, est obcaecati repellat iste maxime perferendis debitis repudiandae beatae pariatur qui quo? Sint blanditiis, totam quaerat vel eum eaque recusandae in, ullam commodi, laudantium est autem quos cupiditate qui saepe! Ipsam amet placeat harum at, architecto sequi natus ex pariatur omnis eum, magnam, ea nulla similique nihil minima aut laudantium doloremque rerum. Excepturi veritatis, accusamus quibusdam ad explicabo velit facilis eius assumenda dolor laboriosam, ex libero provident, omnis repellendus cum error facere unde amet? Labore minus nesciunt saepe totam quasi commodi, expedita alias ullam, doloribus tempora sapiente beatae illo reprehenderit, iure nobis voluptas veritatis corrupti dolor id non velit maiores aliquid quia! Amet inventore est deserunt consequatur minus omnis reprehenderit cumque optio pariatur. Rerum perspiciatis, ullam voluptatibus architecto, quisquam nemo debitis nostrum, itaque suscipit impedit quo velit consequuntur minima accusantium beatae quos est quae. Omnis cum ab sapiente, facilis distinctio at numquam ut hic quaerat sunt maxime suscipit accusamus eos aspernatur corrupti modi cumque quasi maiores, inventore voluptate natus. Quibusdam deserunt libero consectetur fuga debitis accusantium tempora, nesciunt temporibus! Aliquid illo a eum cumque eveniet reiciendis recusandae alias hic, quasi iusto laudantium culpa id nihil natus praesentium dicta laborum eos explicabo dolore vel dolorum dolores soluta. Eius corporis illum ipsa numquam voluptatibus nemo doloremque laborum ea unde voluptatem id facilis in, aspernatur voluptas amet atque cum quas consectetur eaque. Nostrum quia nulla iste ullam, maxime atque itaque!
        <br />
        <br />
        welcome {props.currentUser.email}
    </div>
  )
}

export default HomePage