import React from 'react'

function DetailsPage() {
  return (
    <div>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Neque pariatur enim iusto iure. Fuga molestias quisquam consequuntur mollitia hic saepe ea est labore a. Ipsum quo magnam reiciendis? Consequuntur, sapiente enim temporibus perspiciatis blanditiis reprehenderit perferendis consequatur placeat totam reiciendis eaque libero distinctio dicta possimus, odit cupiditate dolores voluptate soluta veniam pariatur fuga laborum vitae! Sit eaque corrupti, odio facilis tempore itaque sapiente totam fugiat tenetur delectus, voluptatem veritatis enim culpa iusto nostrum at expedita, amet ullam commodi ratione unde eligendi maiores. Sequi, alias minus? Rerum numquam sequi iure? Rem tempore iusto doloremque iste voluptates pariatur provident reprehenderit ipsum facilis eius, explicabo perspiciatis autem fuga quo veritatis minus consectetur laborum, ut cum nulla voluptatum? Libero fugit in rerum ea cupiditate ullam repudiandae officia. Eligendi aliquid asperiores assumenda provident. Excepturi reprehenderit delectus voluptatum debitis quae possimus dignissimos, eum unde maiores sed, quasi ea numquam! Eaque ducimus, veniam aperiam repellat aut saepe magni fugit, maxime tempora, explicabo itaque natus soluta dignissimos! Delectus illum quaerat, corporis numquam iure harum dolor molestiae excepturi sed non at veniam voluptates minus sapiente perferendis incidunt consequatur ullam repellendus. Quasi iure quod a, magnam rerum debitis! Ex perferendis temporibus autem vitae ipsum quas officiis dolorum non praesentium commodi odio porro saepe nobis omnis esse reprehenderit, numquam nulla, pariatur iste consectetur et aliquam. Quidem libero voluptates saepe expedita dolore earum voluptas. Temporibus deleniti placeat eveniet aliquam libero facere perferendis rerum at quis reiciendis tempora soluta, qui, dignissimos corporis illo enim. In facilis perspiciatis consequuntur iusto dolores ipsam dolore ducimus amet neque eos praesentium tenetur fugit, voluptate expedita nesciunt ab similique ratione quidem voluptatibus. Minus aperiam error deserunt optio harum libero veniam magnam ducimus necessitatibus velit, labore impedit quo delectus iste inventore aliquid doloremque illum iure ut voluptatem incidunt facilis accusantium eos tenetur. Aliquid numquam eius, nisi consequuntur doloribus eum, harum pariatur aliquam temporibus dicta corrupti cum error culpa. Maxime, fugiat cum fugit mollitia suscipit exercitationem veniam veritatis explicabo possimus ut tenetur aliquam laborum aut vitae molestias nihil ducimus dolorem, omnis totam laudantium amet molestiae libero incidunt dignissimos! Repudiandae eum ab facilis sed voluptas! Ipsa sequi voluptatem a deserunt nesciunt.
        
    </div>
  )
}

export default DetailsPage